server:
  port: 8080

  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/DIYO
    username: root
    password: 1234pass

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update

    show-sql: true


city: New York



